/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/persons/{person_id}/photo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Person Photo */
        get: operations["person_photo_persons__person_id__photo_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/persons": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Persons
         * @description Browse legislators (directory). Optionally filter by house. Ordered by declared assets desc.
         */
        get: operations["list_persons_persons_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/persons/{person_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Person
         * @description Full resume for one legislator.
         */
        get: operations["get_person_persons__person_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search
         * @description Fuzzy search legislators by name (uses person.normalized_name trigram index).
         */
        get: operations["search_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AffidavitWealth */
        AffidavitWealth: {
            /** Election Cycle */
            election_cycle: string;
            /** Filed Year */
            filed_year: number;
            /** Total Assets */
            total_assets: number;
            /** Total Liabilities */
            total_liabilities: number;
            /** Movable Assets */
            movable_assets?: number | null;
            /** Immovable Assets */
            immovable_assets?: number | null;
            /** Self Income */
            self_income?: number | null;
            source: components["schemas"]["Source"];
        };
        /** CriminalCase */
        CriminalCase: {
            /** Case Number */
            case_number: string | null;
            /** Court */
            court: string | null;
            /** Filed Year */
            filed_year: number | null;
            /** Status */
            status: string;
            /** Is Convicted */
            is_convicted: boolean;
            /** Severity */
            severity: ("heinous" | "serious" | "minor") | null;
            /** Sections */
            sections: string[];
            /** Description */
            description: string | null;
            source: components["schemas"]["Source"];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** OfficeTerm */
        OfficeTerm: {
            /** House */
            house: string;
            /** Cycle Number */
            cycle_number: number;
            /** Constituency */
            constituency: string | null;
            /** State */
            state: string | null;
            /** Party */
            party: string | null;
            /** Membership Type */
            membership_type: string;
            /** Start Date */
            start_date: string | null;
            /** End Date */
            end_date: string | null;
            /** Status */
            status: string;
            source: components["schemas"]["Source"];
            /** Attendance Pct */
            attendance_pct?: number | null;
            attendance_source?: components["schemas"]["Source"] | null;
        };
        /** PartyStint */
        PartyStint: {
            /** Party */
            party: string;
            /** Joined Date */
            joined_date: string | null;
            /** Left Date */
            left_date: string | null;
            /** Is Current */
            is_current: boolean;
            /** Join Reason */
            join_reason: string | null;
            /** Leave Reason */
            leave_reason: string | null;
            reason_source: components["schemas"]["Source"] | null;
            source: components["schemas"]["Source"];
        };
        /** PartySwitch */
        PartySwitch: {
            /** From Party */
            from_party: string | null;
            /** To Party */
            to_party: string;
            /** Event Date */
            event_date: string | null;
            /** Narrative */
            narrative: string | null;
            source: components["schemas"]["Source"] | null;
        };
        /** PersonResume */
        PersonResume: {
            /** Id */
            id: number;
            /** Display Name */
            display_name: string;
            /** Native Name */
            native_name?: string | null;
            /** Photo Url */
            photo_url?: string | null;
            /** Age */
            age?: number | null;
            /** Education */
            education?: string | null;
            /** Office Terms */
            office_terms: components["schemas"]["OfficeTerm"][];
            /** Party History */
            party_history: components["schemas"]["PartyStint"][];
            /**
             * Party Switches
             * @default []
             */
            party_switches: components["schemas"]["PartySwitch"][];
            /** Wealth */
            wealth: components["schemas"]["AffidavitWealth"][];
            /** Criminal Cases */
            criminal_cases: components["schemas"]["CriminalCase"][];
        };
        /** PersonSummary */
        PersonSummary: {
            /** Id */
            id: number;
            /** Display Name */
            display_name: string;
            /** Native Name */
            native_name?: string | null;
            /** Photo Url */
            photo_url?: string | null;
            /** Current Party */
            current_party: string | null;
            /** Current House */
            current_house: string | null;
            /** Constituency */
            constituency: string | null;
            /** Net Assets */
            net_assets?: number | null;
            /**
             * Pending Cases
             * @default 0
             */
            pending_cases: number;
            /**
             * Total Cases
             * @default 0
             */
            total_cases: number;
            /** Top Severity */
            top_severity?: ("heinous" | "serious" | "minor") | null;
            /** Current Attendance Pct */
            current_attendance_pct?: number | null;
        };
        /** Source */
        Source: {
            /** Code */
            code: string;
            /** Name */
            name: string;
            /** Url */
            url?: string | null;
            /** Trust Tier */
            trust_tier: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    person_photo_persons__person_id__photo_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                person_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_persons_persons_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                house?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_person_persons__person_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                person_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonResume"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_search_get: {
        parameters: {
            query: {
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
