/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/persons/{person_id}/photo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Person Photo */
        get: operations["person_photo_persons__person_id__photo_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/persons": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Persons
         * @description Browse legislators (directory): filter by house/state/constituency/jurisdiction/party/cases/theme/
         *     search, sort by assets|cases|attendance|theme_questions|name, and page via limit/offset. `cycle` (a Lok
         *     Sabha cycle number) browses that session's roster as it stood at the time. Total match count is returned
         *     in the `X-Total-Count` response header (the body stays a plain list).
         */
        get: operations["list_persons_persons_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/persons/facets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Person Facets
         * @description Dropdown option lists (party / state / house / LS session, each with a count) for a browse scope.
         */
        get: operations["person_facets_persons_facets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/persons/{person_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Person
         * @description Full resume for one legislator.
         */
        get: operations["get_person_persons__person_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/questions/{question_id}/document": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Question Document */
        get: operations["question_document_questions__question_id__document_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/debates/{debate_id}/document": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Debate Document */
        get: operations["debate_document_debates__debate_id__document_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/parliament/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Parliament Stats
         * @description National dashboard: totals + theme mix + top ministries + most-active MPs, for the given house.
         */
        get: operations["parliament_stats_parliament_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/parliament/ministries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Parliament Ministries
         * @description The full ranked list of ministries by question count, for the given house.
         */
        get: operations["parliament_ministries_parliament_ministries_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/parliament/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Parliament Search
         * @description Topic search over question subjects + debate titles for the given house. Filter by kind/theme, page via
         *     limit/offset; the total match count is in the `X-Total-Count` header (body stays a plain list).
         */
        get: operations["parliament_search_parliament_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/parliament/trends": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Parliament Trends
         * @description Monthly question volume split by policy theme, for the given house — the stacked-area trends view.
         */
        get: operations["parliament_trends_parliament_trends_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/aggregate/theme-focus": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Theme Focus
         * @description Theme-emphasis mix per party or state, for the given house: each group's policy-theme shares + volume.
         */
        get: operations["theme_focus_aggregate_theme_focus_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search
         * @description Fuzzy search legislators by name (uses person.normalized_name trigram index).
         */
        get: operations["search_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Stats
         * @description Real counts (total / per house / with cases / crorepatis) — not capped by any list limit.
         */
        get: operations["get_stats_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/visits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Visits
         * @description Current lifetime unique-visitor count (no increment).
         */
        get: operations["get_visits_visits_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/visits/hit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Hit
         * @description Atomically increment the unique-visitor count and return the new total.
         */
        post: operations["hit_visits_hit_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/elections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Elections
         * @description All registered elections. Past entries carry a winner_count + house (results reuse /persons?house=…).
         */
        get: operations["list_elections_elections_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/indicators/india": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * India
         * @description The full India Dashboard: every catalogued macro series (history + latest), grouped by category.
         */
        get: operations["india_indicators_india_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActivityMetric */
        ActivityMetric: {
            /** Value */
            value: number | null;
            /** House Median */
            house_median?: number | null;
            /** Percentile */
            percentile?: number | null;
        };
        /** AffidavitWealth */
        AffidavitWealth: {
            /** Election Cycle */
            election_cycle: string;
            /** Filed Year */
            filed_year: number;
            /** Total Assets */
            total_assets: number;
            /** Total Liabilities */
            total_liabilities: number;
            /** Movable Assets */
            movable_assets?: number | null;
            /** Immovable Assets */
            immovable_assets?: number | null;
            /** Self Income */
            self_income?: number | null;
            source: components["schemas"]["Source"];
        };
        /**
         * AggregateGroup
         * @description One party or state's collective question profile (18th Lok Sabha).
         */
        AggregateGroup: {
            /** Key */
            key: string;
            /** Total */
            total: number;
            /** Mps */
            mps: number;
            /** Themes */
            themes: components["schemas"]["ThemeShare"][];
        };
        /** ChargeSection */
        ChargeSection: {
            /** Raw */
            raw: string;
            /** Title */
            title?: string | null;
            /** Equivalent */
            equivalent?: string | null;
        };
        /** Contact */
        Contact: {
            /** Channel Type */
            channel_type: string;
            /** Value */
            value: string;
            /** Label */
            label: string | null;
            source: components["schemas"]["Source"];
        };
        /** CriminalCase */
        CriminalCase: {
            /** Case Number */
            case_number: string | null;
            /** Court */
            court: string | null;
            /** Filed Year */
            filed_year: number | null;
            /** Status */
            status: string;
            /** Is Convicted */
            is_convicted: boolean;
            /** Severity */
            severity: ("heinous" | "serious" | "minor") | null;
            /** Sections */
            sections: components["schemas"]["ChargeSection"][];
            /** Description */
            description: string | null;
            source: components["schemas"]["Source"];
        };
        /** Election */
        Election: {
            /** Eci Election Id */
            eci_election_id: string | null;
            /** Name */
            name: string;
            /** Level */
            level: string;
            /** Status */
            status: string;
            /** Election Date */
            election_date: string | null;
            /** Seats */
            seats: number | null;
            /** House */
            house: string | null;
            /** Winner Count */
            winner_count: number;
            /** Note */
            note?: string | null;
        };
        /** FacetCount */
        FacetCount: {
            /** Value */
            value: string;
            /** Count */
            count: number;
        };
        /**
         * Facets
         * @description Dropdown option lists for a browse scope (party / state / house / theme), each with its row count.
         */
        Facets: {
            /**
             * Parties
             * @default []
             */
            parties: components["schemas"]["FacetCount"][];
            /**
             * States
             * @default []
             */
            states: components["schemas"]["FacetCount"][];
            /**
             * Houses
             * @default []
             */
            houses: components["schemas"]["FacetCount"][];
            /**
             * Themes
             * @default []
             */
            themes: components["schemas"]["FacetCount"][];
            /**
             * Cycles
             * @default []
             */
            cycles: components["schemas"]["FacetCount"][];
        };
        /**
         * FirstOffice
         * @description The earliest public office on record — a person's 'entered public life' anchor.
         *
         *     Derived (not stored): the earliest-dated of the person's office_terms and leadership roles. It's only
         *     as deep as the sourced record reaches, so it's a floor ('at least since'), never a claim of the very
         *     first office ever held. Carries the provenance of whichever fact it was derived from.
         */
        FirstOffice: {
            /** Year */
            year: number;
            /** Label */
            label: string;
            /** Kind */
            kind: string;
            source: components["schemas"]["Source"];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * IndiaDashboard
         * @description The India Dashboard aggregate — country-level macro indicators, grouped by category.
         *
         *     Descriptive official statistics (World Bank Open Data, CC-BY 4.0, trust tier 1) — what the record
         *     says, never a judgment. Every series carries its own source link and its latest year (series lag
         *     differs: GDP is near-current, survey series like the Gini update only in survey years).
         */
        IndiaDashboard: {
            /** Country */
            country: string;
            /** Categories */
            categories: components["schemas"]["IndicatorCategory"][];
            /** Total Indicators */
            total_indicators: number;
        };
        /** IndicatorCategory */
        IndicatorCategory: {
            /** Name */
            name: string;
            /** Indicators */
            indicators: components["schemas"]["IndicatorSeries"][];
        };
        /** IndicatorPoint */
        IndicatorPoint: {
            /** Year */
            year: number;
            /** Value */
            value: number;
        };
        /**
         * IndicatorSeries
         * @description One macro series (e.g. GDP) — full yearly history + the latest value, with provenance.
         */
        IndicatorSeries: {
            /** Code */
            code: string;
            /** Name */
            name: string;
            /** Unit */
            unit: string;
            /** Format */
            format: string;
            /**
             * Polarity
             * @default 0
             */
            polarity: number;
            /** Note */
            note?: string | null;
            /** Latest Value */
            latest_value: number;
            /** Latest Year */
            latest_year: number;
            /** Points */
            points: components["schemas"]["IndicatorPoint"][];
            source: components["schemas"]["Source"];
        };
        /** MinistryCount */
        MinistryCount: {
            /** Ministry */
            ministry: string;
            /** Theme */
            theme: string;
            /** Count */
            count: number;
        };
        /** MpCount */
        MpCount: {
            /** Id */
            id: number;
            /** Display Name */
            display_name: string;
            /** Photo Url */
            photo_url?: string | null;
            /** Count */
            count: number;
            /** Top Theme */
            top_theme?: string | null;
        };
        /** NewsItem */
        NewsItem: {
            /** Title */
            title: string;
            /** Snippet */
            snippet?: string | null;
            /** Url */
            url: string;
            /** Publisher */
            publisher?: string | null;
            /** Published At */
            published_at?: string | null;
            source: components["schemas"]["Source"];
        };
        /** OfficeTerm */
        OfficeTerm: {
            /** House */
            house: string;
            /** Cycle Number */
            cycle_number: number;
            /** Constituency */
            constituency: string | null;
            /** State */
            state: string | null;
            /** Party */
            party: string | null;
            /** Membership Type */
            membership_type: string;
            /** Start Date */
            start_date: string | null;
            /** End Date */
            end_date: string | null;
            /** Status */
            status: string;
            source: components["schemas"]["Source"];
            /** Attendance Pct */
            attendance_pct?: number | null;
            attendance_source?: components["schemas"]["Source"] | null;
        };
        /**
         * ParliamentStats
         * @description Institutional-lens dashboard: what the House is asking (currently the 18th Lok Sabha).
         */
        ParliamentStats: {
            /** House */
            house: string;
            /** Total Questions */
            total_questions: number;
            /** Total Debates */
            total_debates: number;
            /** Active Mps */
            active_mps: number;
            /** Themes */
            themes: components["schemas"]["ThemeCount"][];
            /** Top Ministries */
            top_ministries: components["schemas"]["MinistryCount"][];
            /** Most Active */
            most_active: components["schemas"]["MpCount"][];
        };
        /**
         * ParliamentaryActivity
         * @description What an MP did in the House — counts with peer context, from PRS MP Track (CC-BY 4.0).
         */
        ParliamentaryActivity: {
            /** House */
            house: string;
            questions: components["schemas"]["ActivityMetric"];
            debates: components["schemas"]["ActivityMetric"];
            private_member_bills: components["schemas"]["ActivityMetric"];
            /** Period Start */
            period_start?: string | null;
            /** Period End */
            period_end?: string | null;
            source: components["schemas"]["Source"];
        };
        /** ParliamentaryDebate */
        ParliamentaryDebate: {
            /** Id */
            id: number;
            /** Title */
            title?: string | null;
            /** Debate Type */
            debate_type?: string | null;
            /** Debate Date */
            debate_date?: string | null;
            /** Document Url */
            document_url?: string | null;
        };
        /** ParliamentaryQuestion */
        ParliamentaryQuestion: {
            /** Id */
            id: number;
            /** Subject */
            subject?: string | null;
            /** Ministry */
            ministry?: string | null;
            /** Theme */
            theme?: string | null;
            /** Question Type */
            question_type?: string | null;
            /** Asked Date */
            asked_date?: string | null;
            /** Document Url */
            document_url?: string | null;
        };
        /**
         * ParliamentaryRecord
         * @description Individual questions asked + debates joined — the content behind the activity counts.
         *
         *     Enumerated from PRS MP Track profiles (CC-BY 4.0). `*_count` is the full total; the lists are capped
         *     (most-recent first) to bound payload — the UI shows "showing N of total".
         */
        ParliamentaryRecord: {
            /** House */
            house: string;
            /** Questions Count */
            questions_count: number;
            /** Debates Count */
            debates_count: number;
            /** Questions */
            questions: components["schemas"]["ParliamentaryQuestion"][];
            /** Debates */
            debates: components["schemas"]["ParliamentaryDebate"][];
            /**
             * Thematic Focus
             * @default []
             */
            thematic_focus: components["schemas"]["ThemeFocus"][];
            source: components["schemas"]["Source"];
        };
        /** PartyStint */
        PartyStint: {
            /** Party */
            party: string;
            /** Joined Date */
            joined_date: string | null;
            /** Left Date */
            left_date: string | null;
            /** Is Current */
            is_current: boolean;
            /** Join Reason */
            join_reason: string | null;
            /** Leave Reason */
            leave_reason: string | null;
            reason_source: components["schemas"]["Source"] | null;
            source: components["schemas"]["Source"];
        };
        /** PartySwitch */
        PartySwitch: {
            /** From Party */
            from_party: string | null;
            /** To Party */
            to_party: string;
            /** Event Date */
            event_date: string | null;
            /** Narrative */
            narrative: string | null;
            source: components["schemas"]["Source"] | null;
        };
        /** PersonResume */
        PersonResume: {
            /** Id */
            id: number;
            /** Display Name */
            display_name: string;
            /** Native Name */
            native_name?: string | null;
            /** Photo Url */
            photo_url?: string | null;
            /** Age */
            age?: number | null;
            /** Education */
            education?: string | null;
            /** Relative Name */
            relative_name?: string | null;
            /** Home State */
            home_state?: string | null;
            first_office?: components["schemas"]["FirstOffice"] | null;
            /** Office Terms */
            office_terms: components["schemas"]["OfficeTerm"][];
            /**
             * Roles
             * @default []
             */
            roles: components["schemas"]["RoleEntry"][];
            /**
             * Contacts
             * @default []
             */
            contacts: components["schemas"]["Contact"][];
            /** Party History */
            party_history: components["schemas"]["PartyStint"][];
            /**
             * Party Switches
             * @default []
             */
            party_switches: components["schemas"]["PartySwitch"][];
            /** Wealth */
            wealth: components["schemas"]["AffidavitWealth"][];
            /** Criminal Cases */
            criminal_cases: components["schemas"]["CriminalCase"][];
            activity?: components["schemas"]["ParliamentaryActivity"] | null;
            parliamentary_record?: components["schemas"]["ParliamentaryRecord"] | null;
            /**
             * News
             * @default []
             */
            news: components["schemas"]["NewsItem"][];
        };
        /** PersonSummary */
        PersonSummary: {
            /** Id */
            id: number;
            /** Display Name */
            display_name: string;
            /** Native Name */
            native_name?: string | null;
            /** Photo Url */
            photo_url?: string | null;
            /** Current Party */
            current_party: string | null;
            /** Current House */
            current_house: string | null;
            /** Constituency */
            constituency: string | null;
            /** State */
            state?: string | null;
            /** Net Assets */
            net_assets?: number | null;
            /** Age */
            age?: number | null;
            /** Education */
            education?: string | null;
            /** Gender */
            gender?: string | null;
            /**
             * Pending Cases
             * @default 0
             */
            pending_cases: number;
            /**
             * Total Cases
             * @default 0
             */
            total_cases: number;
            /** Top Severity */
            top_severity?: ("heinous" | "serious" | "minor") | null;
            /** Current Attendance Pct */
            current_attendance_pct?: number | null;
            /** Questions Count */
            questions_count?: number | null;
            /** Top Theme */
            top_theme?: string | null;
        };
        /**
         * RecordHit
         * @description One topic-search hit — a question or debate matching the query (18th Lok Sabha).
         */
        RecordHit: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "question" | "debate";
            /** Id */
            id: number;
            /** Title */
            title?: string | null;
            /** Mp Id */
            mp_id: number;
            /** Mp Name */
            mp_name: string;
            /** Ministry */
            ministry?: string | null;
            /** Theme */
            theme?: string | null;
            /** Date */
            date?: string | null;
        };
        /** RoleEntry */
        RoleEntry: {
            /** Role Type */
            role_type: string;
            /** Title */
            title: string | null;
            /** Body */
            body: string | null;
            /** House */
            house: string | null;
            /** Portfolio */
            portfolio: string | null;
            /** Start Date */
            start_date: string | null;
            /** End Date */
            end_date: string | null;
            /** Status */
            status: string;
            source: components["schemas"]["Source"];
        };
        /** Source */
        Source: {
            /** Code */
            code: string;
            /** Name */
            name: string;
            /** Url */
            url?: string | null;
            /** Trust Tier */
            trust_tier: number;
        };
        /** Stats */
        Stats: {
            /** Total Legislators */
            total_legislators: number;
            /** Lok Sabha */
            lok_sabha: number;
            /** Rajya Sabha */
            rajya_sabha: number;
            /** With Cases */
            with_cases: number;
            /** Crorepatis */
            crorepatis: number;
        };
        /** ThemeCount */
        ThemeCount: {
            /** Theme */
            theme: string;
            /** Count */
            count: number;
        };
        /**
         * ThemeFocus
         * @description One policy theme's weight in an MP's questions, vs the House — the 'Policy focus' breakdown.
         *
         *     Descriptive topical emphasis derived from the official ministry each question addressed (never a value
         *     judgment). `share` = this MP's fraction of questions in the theme; `house_share` = the same fraction
         *     pooled across all sitting members of the house (None until the house corpus is large enough to average).
         */
        ThemeFocus: {
            /** Theme */
            theme: string;
            /** Count */
            count: number;
            /** Share */
            share: number;
            /** House Share */
            house_share?: number | null;
        };
        /**
         * ThemeFocusBreakdown
         * @description Descriptive theme-emphasis breakdown by party or state — what a group's members collectively raise.
         *
         *     Topical emphasis derived from the official ministry each question addressed; a comparison of focus, never
         *     a value judgment or productivity ranking (same ethic as the per-MP 'Policy focus'). Missing ≠ zero.
         */
        ThemeFocusBreakdown: {
            /**
             * By
             * @enum {string}
             */
            by: "party" | "state";
            /** House */
            house: string;
            /** Groups */
            groups: components["schemas"]["AggregateGroup"][];
        };
        /** ThemeSeries */
        ThemeSeries: {
            /** Theme */
            theme: string;
            /** Points */
            points: number[];
        };
        /** ThemeShare */
        ThemeShare: {
            /** Theme */
            theme: string;
            /** Count */
            count: number;
            /** Share */
            share: number;
        };
        /**
         * Trends
         * @description Monthly question volume split by policy theme (stacked-area trends over the term).
         */
        Trends: {
            /** House */
            house: string;
            /** Months */
            months: string[];
            /** Totals */
            totals: number[];
            /** Series */
            series: components["schemas"]["ThemeSeries"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VisitCount */
        VisitCount: {
            /** Count */
            count: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    person_photo_persons__person_id__photo_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                person_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_persons_persons_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                house?: string | null;
                state?: string | null;
                constituency?: string | null;
                jurisdiction?: string | null;
                party?: string | null;
                cases?: string | null;
                q?: string | null;
                theme?: string | null;
                cycle?: number | null;
                sort?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    person_facets_persons_facets_get: {
        parameters: {
            query?: {
                house?: string | null;
                state?: string | null;
                jurisdiction?: string | null;
                cycle?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Facets"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_person_persons__person_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                person_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonResume"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    question_document_questions__question_id__document_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                question_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    debate_document_debates__debate_id__document_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                debate_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    parliament_stats_parliament_stats_get: {
        parameters: {
            query?: {
                house?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParliamentStats"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    parliament_ministries_parliament_ministries_get: {
        parameters: {
            query?: {
                house?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MinistryCount"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    parliament_search_parliament_search_get: {
        parameters: {
            query: {
                q: string;
                kind?: string | null;
                theme?: string | null;
                limit?: number;
                offset?: number;
                house?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecordHit"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    parliament_trends_parliament_trends_get: {
        parameters: {
            query?: {
                house?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Trends"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    theme_focus_aggregate_theme_focus_get: {
        parameters: {
            query: {
                by: string;
                house?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ThemeFocusBreakdown"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_search_get: {
        parameters: {
            query: {
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_stats_stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Stats"];
                };
            };
        };
    };
    get_visits_visits_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VisitCount"];
                };
            };
        };
    };
    hit_visits_hit_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VisitCount"];
                };
            };
        };
    };
    list_elections_elections_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Election"][];
                };
            };
        };
    };
    india_indicators_india_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IndiaDashboard"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
