apiVersion: v1
kind: Service
metadata:
  name: neta-control
  labels:
    app.kubernetes.io/name: neta-control
    app.kubernetes.io/component: control-plane
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: neta-control
  ports:
    - name: http
      port: 8001
      targetPort: http
      protocol: TCP
