apiVersion: v1
kind: ServiceAccount
metadata:
  name: neta-control
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: neta-reconciler
automountServiceAccountToken: false
