apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: neta-production-workloads
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: neta-production
  source:
    repoURL: https://github.com/citizen-apps-india/neta-resume.git
    targetRevision: main
    path: deploy/k8s/overlays/production
  destination:
    name: neta-production
    namespace: neta-production
  revisionHistoryLimit: 5
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
      - ApplyOutOfSyncOnly=true
      - PruneLast=true
