apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dagster-postgresql
spec:
  refreshPolicy: Periodic
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: neta-runtime-store
  target:
    name: dagster-postgresql
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: postgresql-password
      remoteRef:
        key: neta/production/runtime
        property: DAGSTER_POSTGRES_PASSWORD
