apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - runtime-external-secret.yaml
  - dagster-postgres-external-secret.yaml
labels:
  - pairs:
      app.kubernetes.io/part-of: neta-resume
      app.kubernetes.io/managed-by: argocd
    includeSelectors: false
